---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-go-api
  namespace: sandbox
  labels:
    app: template-go-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-go-api
  template:
    metadata:
      labels:
        app: template-go-api
    spec:
      containers:
        - name: template-go-api
          image: resuelve/template-go-api:latest
          ports:
            - containerPort: 5001
          env:
            - name: PG_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: template-go-api-secret
                  key: PG_DB_HOST
            - name: PG_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: template-go-api-secret
                  key: PG_DB_PORT
            - name: PG_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: template-go-api-secret
                  key: PG_DB_NAME
            - name: PG_DB_SSLMODE
              valueFrom:
                secretKeyRef:
                  name: template-go-api-secret
                  key: PG_DB_SSLMODE
            - name: PG_DB_USER
              valueFrom:
                secretKeyRef:
                  name: template-go-api-secret
                  key: PG_DB_USER
            - name: PG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: template-go-api-secret
                  key: PG_DB_PASSWORD
      imagePullSecrets:
        - name: docker-secrets
      nodeSelector:
        cloud.google.com/gke-nodepool: "sandbox"
