---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gha-deployer-sandbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gha-deployer-sandbox
subjects:
  - kind: ServiceAccount
    namespace: sandbox
    name: gha-deployer-sandbox
