name: 'iam'

on:
  push:
    branches:
    - master
    paths:
      - 'iam/**'
  pull_request:
    paths:
      - 'iam/**'

jobs:
  terraform:
    name: 'Create IAM resources'
    runs-on: ubuntu-latest
    environment: sandbox
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.10
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.SANDBOX_GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.SANDBOX_GCP_SA_KEY }}
        export_default_credentials: true
    - name: Terraform Init plugins
      run: cd iam; terraform init
    - name: Terraform Format check
      run: cd iam; terraform fmt -check
    - name: Terraform Plan
      run: cd iam; terraform plan
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: cd iam; terraform apply -auto-approve

